# Generated by Django 4.2.16 on 2024-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Number', models.CharField(max_length=50)),
                ('Details', models.CharField(max_length=50)),
                ('Photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
